### ISSUE TITLE
`CompletionItemKind` is unknown

### ISSUE THREAD

**Issue by mathjiajia** [mikavilpas/blink-ripgrep.nvim#60]
Is it possible to add something below?
```lua
kind = require('blink.cmp.types').CompletionItemKind.Text
```
otherwise, each completion item is `unknown` type for blink.

**Comment by mikavilpas** [comment]
Here is a workaround:

```lua
  {
    "saghen/blink.cmp",
    event = "VeryLazy",
    version = "v0.8.0",

    ---@module 'blink.cmp'
    ---@type blink.cmp.Config
    opts = {
      sources = {
        default = {
          "buffer",
          "ripgrep",
        },
        providers = {
          ripgrep = {
            module = "blink-ripgrep",
            name = "Ripgrep",
            transform_items = function(_, items)
              for _, item in ipairs(items) do
                item.kind = require("blink.cmp.types").CompletionItemKind.Field
              end
              return items
            end,
            ---@type blink-ripgrep.Options
            opts = {},
          },
        },
      },
    }
  }
```

Blink seems to provide this way of customizing the items. Let's keep this issue open while I think about this.

I originally set it to unknown because it looked too visually similar to other completion items. For me, it's useful to make this distinction because typically everything else is more relevant to the current context.

It's a bit of a hack - maybe there is another way to distinguish them that I can't think of yet.

**Comment by mikavilpas** [comment]
I just enabled this by default, it's a good idea 👍🏻
